<?php
//000000086400a:11:{s:2:"id";s:1:"1";s:4:"name";s:4:"user";s:5:"title";s:15:"用户信息表";s:7:"need_pk";s:1:"0";s:10:"field_sort";s:250:"["come_from","nickname","password","truename","mobile","email","sex","headimgurl","city","province","country","language","score","experience","unionid","login_count","reg_ip","reg_time","last_login_ip","last_login_time","status","is_init","is_audit"]";s:9:"list_grid";s:267:"headimgurl|url_img_html:头像
login_name:登录账号
login_password:登录密码
nickname:用户昵称
sex:性别
group:分组
score:金币值
experience:经历值
ids:操作:set_login?uid=[uid]|设置登录账号,detail?uid=[uid]|详细资料,[EDIT]|编辑";s:8:"list_row";s:2:"20";s:10:"search_key";s:0:"";s:11:"engine_type";s:6:"MyISAM";s:5:"addon";s:4:"Core";s:8:"file_md5";s:32:"d0eba6dea42a7ce969cac77905c12b2d";}
?>