<?php
//000000086400a:11:{s:2:"id";s:3:"188";s:4:"name";s:13:"lottery_games";s:5:"title";s:12:"抽奖游戏";s:7:"need_pk";s:1:"1";s:10:"field_sort";s:155:"["title","keyword","game_type","start_time","end_time","status","day_attend_limit","attend_limit","day_win_limit","win_limit","day_winners_count","remark"]";s:9:"list_grid";s:353:"id:序号
title:活动名称
game_type:游戏类型
keyword:关键词
start_time|time_format:开始时间
end_time|time_format:结束时间
status:活动状态
attend_num:参与人数
winners_list:中奖人列表
ids:操作:[EDIT]|编辑,[DELETE]|删除,preview&games_id=[id]|预览,index&_addons=Draw&_controller=Wap&games_id=[id]|复制链接";s:8:"list_row";s:2:"10";s:10:"search_key";s:0:"";s:11:"engine_type";s:6:"MyISAM";s:5:"addon";s:4:"Draw";s:8:"file_md5";s:32:"0ffb2d8a42e01c0d3b549ff6da0f0ba5";}
?>